version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - libpulse0
    - p7zip-full
    - libasound2
    - libssl-dev
  tools:
    python: "3.11"

  jobs:
    pre_build:
      - "pip install hatch"
      - "hatch run sdk-download"

    build:
      - "hatch run docs:build"
